# generated by DipDup 8.4.2

from __future__ import annotations

from typing import TypedDict


class V183(TypedDict):
    """
    Liquidity of an asset was added to a pool.
    """

    pool_id: int
    who: str
    shares: int
    assets: list[str]
