# generated by DipDup 8.3.3


from typing import TypedDict

from dex_screener.models.dex_fields import Account


class V115(TypedDict):
    """
    LP Position was created and NFT instance minted.
    """

    position_id: int
    owner: Account
    asset: int
    amount: int
    shares: int
    price: int
