# generated by DipDup 8.4.0

from __future__ import annotations

from typing import TypedDict


class V115(TypedDict):
    """
    LP Position was created and NFT instance minted.
    """

    position_id: int
    owner: str
    asset: int
    amount: int
    shares: int
    price: int
