# generated by DipDup 8.3.3

from __future__ import annotations

from typing import TYPE_CHECKING
from typing import TypedDict

if TYPE_CHECKING:
    from dex_screener.models.dex_fields import Account


class V115(TypedDict):
    """
    Buy trade executed.
    """

    who: Account
    asset_in: int
    asset_out: int
    amount_in: int
    amount_out: int
