# generated by DipDup 8.3.3

from __future__ import annotations

from typing import TYPE_CHECKING
from typing import TypedDict

if TYPE_CHECKING:
    from dex_screener.models.dex_fields import Account


class V176(TypedDict):
    """
    Purchase executed.
    """

    who: Account
    asset_out: int
    asset_in: int
    amount: int
    buy_price: int
    fee_asset: int
    fee_amount: int
