# generated by DipDup 8.4.0

from __future__ import annotations

from typing import TypedDict


class V176(TypedDict):
    """
    Purchase executed.
    """

    who: str
    asset_out: int
    asset_in: int
    amount: int
    buy_price: int
    fee_asset: int
    fee_amount: int
