# generated by DipDup 8.3.3

from __future__ import annotations

from typing import TypedDict


class V138(TypedDict):
    """
    An Order has been partially filled
    """

    order_id: int
    who: str
    amount_in: int
    amount_out: int
