# generated by DipDup 8.4.1
.PHONY: $(MAKECMDGOALS)
MAKEFLAGS += --no-print-directory
##
##  🚧 DipDup developer tools
##
PACKAGE=dex_screener
TAG=latest
COMPOSE=deploy/compose.yaml

help:           ## Show this help (default)
	@grep -Fh "##" $(MAKEFILE_LIST) | grep -Fv grep -F | sed -e 's/\\$$//' | sed -e 's/##//'

all:            ## Run an entire CI pipeline
	make install format lint test

##

install:        ## Install dependencies
	uv sync --all-extras --all-groups --link-mode symlink --locked

update:         ## Update dependencies
	dipdup self update -q
	uv sync --all-extras --all-groups --link-mode symlink -U

format:         ## Format code with ruff
	ruff format .
	cd reserves; make format

lint:           ## Lint code with ruff and mypy
	ruff check --fix --unsafe-fixes .
	mypy .
	cd reserves; make lint

test:           ## Run tests
	pytest tests

##

image:          ## Build Docker image
	docker buildx build . -f deploy/Dockerfile -t ${PACKAGE}:${TAG} --load
	docker images | grep ${PACKAGE}

init:
	dipdup init --no-base
	cd reserves && dipdup init --no-base

up:             ## Start Compose stack: DB, Hasura, and indexer
	docker-compose -f ${COMPOSE} up -d --build
	docker-compose -f ${COMPOSE} logs -f

down:           ## Stop Compose stack
	docker-compose -f ${COMPOSE} down

##
## Local development
##

up_db:          ## Start Compose stack: DB and Hasura only
	docker-compose -f ${COMPOSE} up -d --build db hasura

run_main:       ## Run main indexer
	dipdup -C compose -e local.env run

run_reserves:   ## Run reserves indexer
	cd reserves; dipdup -C compose -e local.env run

run_proxy:      ## Run Hasura proxy
	python -m dex_screener -C compose -e local.env proxy

only_stableswap:##
	dipdup -C compose -C only-stableswap -e local.env run

only_xyk:       ##
	dipdup -C compose -C only-xyk -e local.env run

only_omnipool:  ##
	dipdup -C compose -C only-omnipool -e local.env run

##

psql:
	docker exec -it dex_screener-db-1 psql -U dipdup dipdup

wipe_main:      ## Wipe public schema
	dipdup -C compose -e local.env schema wipe --force

wipe_reserves:  ## Wipe reserves schema
	cd reserves; dipdup -C compose -e local.env schema wipe --force

##
