[project]
name = "dex-screener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dipdup",
]

[tool.uv.sources]
dipdup = { git = "https://github.com/dipdup-io/dipdup", branch = "next" }
