# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TYPE_CHECKING
from typing import TypedDict

if TYPE_CHECKING:
    from dex_screener.models.dex_fields import Account


class V183(TypedDict):
    """
    Pool was created.
    """

    who: Account
    asset_a: int
    asset_b: int
    initial_shares_amount: int
    share_token: int
    pool: str
