# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TYPE_CHECKING
from typing import TypedDict

if TYPE_CHECKING:
    from dex_screener.models.dex_fields import Account


class V115(TypedDict):
    """
    LP Position was destroyed and NFT instance burned.
    """

    position_id: int
    owner: Account
