# generated by DipDup 8.3.2

from __future__ import annotations

from typing import TypedDict


class V108(TypedDict):
    """
    Native location set for an asset. [asset_id, location]
    """

    asset_id: int
    location: str
