# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict

"""
Currency transfer success.
"""
V108 = TypedDict(
    'V108',
    {
        'currency_id': int,
        'from': str,
        'to': str,
        'amount': int,
    },
)
