# generated by DipDup 8.3.3

from __future__ import annotations

from typing import TypedDict

"""
Transfer succeeded.
"""
V108 = TypedDict(
    'V108',
    {
        'currency_id': int,
        'from': str,
        'to': str,
        'amount': int,
    },
)
