# generated by DipDup 8.3.2

from __future__ import annotations

from typing import TypedDict


class V108(TypedDict):
    """
    Deposit success.
    """

    currency_id: int
    who: str
    amount: int
