# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V183(TypedDict):
    """
    Liquidity was removed from the pool.
    """

    who: str
    asset_a: int
    asset_b: int
    shares: int
