# generated by DipDup 8.4.0

from __future__ import annotations

from typing import TypedDict


class V176(TypedDict):
    """
    Pool was created by the `CreatePool` origin.
    """

    pool: str
    data: str
