# generated by DipDup 8.4.2

from __future__ import annotations

from typing import TypedDict


class V108(TypedDict):
    """
    Update balance success.
    """

    currency_id: int
    who: str
    amount: int
