# generated by DipDup 8.3.2

from __future__ import annotations

from typing import TypedDict

V108 = TypedDict(
    'V108',
    {
        'currency_id': int,
        'from': str,
        'to': str,
        'amount': int,
    },
)
