# generated by DipDup 8.3.3

from __future__ import annotations

from typing import TypedDict


class V205(TypedDict):
    """
    Some amount was minted into an account.
    """

    who: str
    amount: int
