# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V601(TypedDict):
    """
    Some amount was withdrawn from the account (e.g. for transaction fees). [who, value]
    """

    who: str
    value: int
