# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V601(TypedDict):
    """
    Some amount was deposited into the account (e.g. for transaction fees). [who,
    deposit]
    """

    who: str
    deposit: int
