# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V700(TypedDict):
    """
    Some amount was deposited (e.g. for transaction fees).
    """

    who: str
    amount: int
