# generated by DipDup 8.3.2

from __future__ import annotations

from typing import TypedDict


class V115(TypedDict):
    """
    Deposited some balance into an account
    """

    currency_id: int
    who: str
    amount: int
