# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V601(TypedDict):
    """
    Some asset class was created. [asset_id, creator, owner]
    """

    asset_id: int
    creator: str
    owner: str
