# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V700(TypedDict):
    """
    Some asset class was created.
    """

    asset_id: int
    creator: str
    owner: str
