# generated by DipDup 8.3.2

from __future__ import annotations

from typing import TypedDict


class V115(TypedDict):
    """
    LP Position was destroyed and NFT instance burned.
    """

    position_id: int
    owner: str
