# generated by DipDup 8.3.2

from __future__ import annotations

from typing import TypedDict


class V108(TypedDict):
    """
    Metadata set for an asset. [asset_id, symbol, decimals]
    """

    asset_id: int
    symbol: list[int]
    decimals: int
