# generated by DipDup 8.4.0

from __future__ import annotations

from typing import TypedDict


class V108(TypedDict):
    """
    Asset was registered. [asset_id, name, type]
    """

    asset_id: int
    name: list[int]
    type: str
