# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V115(TypedDict):
    """
    Asset was registered.
    """

    asset_id: int
    asset_name: list[int]
    asset_type: str
