# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V222(TypedDict):
    """
    Asset was registered.
    """

    asset_id: int
    asset_name: str
    asset_type: str
    existential_deposit: int
    xcm_rate_limit: str
    symbol: str
    decimals: str
    is_sufficient: str
