# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import List, TypedDict


class V1002000(TypedDict):
    """
    A successful call of the `CretaPool` extrinsic will create this event.
    """

    creator: str
    pool_id: List[str]
    pool_account: str
    lp_token: int
