# generated by DipDup 8.4.2

from __future__ import annotations

from typing import TypedDict


class V183(TypedDict):
    """
    Liquidity removed.
    """

    pool_id: int
    who: str
    shares: int
    amounts: list[str]
    fee: int
