# generated by DipDup 8.3.2

from __future__ import annotations

from typing import TypedDict


class V205(TypedDict):
    """
    Some amount was burned from an account.
    """

    who: str
    amount: int
