# generated by DipDup 8.4.0

from __future__ import annotations

from typing import TypedDict


class V138(TypedDict):
    """
    An Order has been completely filled
    """

    order_id: int
    who: str
    amount_in: int
    amount_out: int
