# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V138(TypedDict):
    """
    An Order has been partially filled
    """

    order_id: int
    who: Account
    amount_in: int
    amount_out: int
