# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict

"""
Transfer succeeded. [from, to, value]
"""
V601 = TypedDict(
    'V601',
    {
        'from': str,
        'to': str,
        'value': int,
    },
)
