# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V183(TypedDict):
    """
    Pool was created.
    """

    who: str
    asset_a: int
    asset_b: int
    initial_shares_amount: int
    share_token: int
    pool: str
