# generated by DipDup 8.4.1

from __future__ import annotations

from typing import TypedDict


class V100(TypedDict):
    """
    A balance was set by root. [who, free, reserved]
    """

    who: str
    free: int
    reserved: int
