# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import List, TypedDict


class V282(TypedDict):
    """
    Trade executed.
    """

    swapper: str
    filler: str
    filler_type: str
    operation: str
    inputs: List[str]
    outputs: List[str]
    fees: List[str]
    operation_stack: List[str]
