# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V601(TypedDict):
    """
    Metadata has been cleared for an asset. [asset_id]
    """

    asset_id: int
