# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V601(TypedDict):
    """
    Some assets were issued. [asset_id, owner, total_supply]
    """

    asset_id: int
    owner: str
    total_supply: int
