# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V9420(TypedDict):
    """
    Some amount was burned from an account.
    """

    who: str
    amount: int
