# generated by DipDup 8.3.2

from __future__ import annotations

from typing import TypedDict


class V138(TypedDict):
    """
    An Order has been placed
    """

    order_id: int
    asset_in: int
    asset_out: int
    amount_in: int
    amount_out: int
    partially_fillable: str
