# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V1003000(TypedDict):
    """
    Pool has been touched in order to fulfill operational requirements.
    """

    pool_id: list[str]
    who: str
