runtimes:
  assethub:
    kind: substrate
    type_registry: assethub

datasources:
  subsquid:
    kind: substrate.subsquid
    url: https://v2.archive.subsquid.io/network/asset-hub-polkadot
  subscan:
    kind: substrate.subscan
    url: https://assethub-polkadot.api.subscan.io/api
  node:
    kind: substrate.node
    url: https://statemint.api.onfinality.io/rpc?apikey=${NODE_API_KEY:-''}
    ws_url: wss://statemint.api.onfinality.io/ws?apikey=${NODE_API_KEY:-''}

indexes:
  assethub_transfers:
    kind: substrate.events
    runtime: assethub
    datasources:
    - subsquid
    - subscan
    - node
    handlers:
      # Native token (DOT)
      - callback: assethub.on_balances_transfer
        name: Balances.Transfer
      - callback: assethub.on_balances_deposit
        name: Balances.Deposit
      - callback: assethub.on_balances_withdraw
        name: Balances.Withdraw
      - callback: assethub.on_balances_burned
        name: Balances.Burned

      # Assets
      - callback: assethub.on_assets_created
        name: Assets.Created
      - callback: assethub.on_assets_issued
        name: Assets.Issued
      - callback: assethub.on_assets_transferred
        name: Assets.Transferred
      - callback: assethub.on_assets_deposited
        name: Assets.Deposited
      - callback: assethub.on_assets_withdrawn
        name: Assets.Withdrawn