runtimes:
  hydradx:
    kind: substrate
    type_registry: hydration

custom:
  native_token:
    name: HDX
    symbol: HDX
    decimals: 12

datasources:
  subsquid:
    kind: substrate.subsquid
    url: https://v2.archive.subsquid.io/network/hydradx
  subscan:
    kind: substrate.subscan
    url: https://hydration.api.subscan.io/api
  node:
    kind: substrate.node
    url: https://hydradx.paras.ibp.network
    ws_url: wss://hydradx.paras.ibp.network
    # url: https://rpc.hydradx.cloud
    # url: https://hydradx-rpc.dwellir.com

indexes:
  hydradx_events:
    kind: substrate.events
    runtime: hydradx
    datasources:
      - subsquid
      - subscan
      - node

    handlers:
      # AssetRegistry
      #
      - callback: hydradx.asset.on_location_set
        name: AssetRegistry.LocationSet
      - callback: hydradx.asset.on_asset_registered
        name: AssetRegistry.Registered
      - callback: hydradx.asset.on_asset_updated
        name: AssetRegistry.Updated
      - callback: hydradx.asset.on_metadata_set
        name: AssetRegistry.MetadataSet
      # XYK
      # (starts at 1439857)
      #
      - callback: hydradx.isolated_pool.on_pool_created
        name: XYK.PoolCreated
      - callback: hydradx.isolated_pool.on_pool_destroyed
        name: XYK.PoolDestroyed
      - callback: hydradx.isolated_pool.on_buy_executed
        name: XYK.BuyExecuted
      - callback: hydradx.isolated_pool.on_sell_executed
        name: XYK.SellExecuted
      - callback: hydradx.isolated_pool.on_liquidity_added
        name: XYK.LiquidityAdded
      - callback: hydradx.isolated_pool.on_liquidity_removed
        name: XYK.LiquidityRemoved
      #
      # Omnipool
      #
      - callback: hydradx.omnipool.on_buy_executed
        name: Omnipool.BuyExecuted
      - callback: hydradx.omnipool.on_sell_executed
        name: Omnipool.SellExecuted
      - callback: hydradx.omnipool.on_position_created
        name: Omnipool.PositionCreated
      - callback: hydradx.omnipool.on_position_destroyed
        name: Omnipool.PositionDestroyed
      - callback: hydradx.omnipool.on_position_updated
        name: Omnipool.PositionUpdated
      #
      # Stableswap
      # (first pool at 3640110)
      #
      - callback: hydradx.stableswap.on_buy_executed
        name: Stableswap.BuyExecuted
      - callback: hydradx.stableswap.on_sell_executed
        name: Stableswap.SellExecuted
      - callback: hydradx.stableswap.on_liquidity_added
        name: Stableswap.LiquidityAdded
      - callback: hydradx.stableswap.on_liquidity_removed
        name: Stableswap.LiquidityRemoved
      - callback: hydradx.otc.on_cancelled
        name: OTC.Cancelled
      - callback: hydradx.otc.on_filled
        name: OTC.Filled
      - callback: hydradx.otc.on_partially_filled
        name: OTC.PartiallyFilled
      - callback: hydradx.otc.on_placed
        name: OTC.Placed
