indexes:
  hydradx_events:
    kind: substrate.events
    runtime: hydradx
    datasources:
      - subsquid
      - subscan
      - node
    handlers:
      # Asset Registry (common)
      - name: AssetRegistry.Registered
        callback: hydradx.asset.on_asset_registered
      - name: AssetRegistry.Updated
        callback: hydradx.asset.on_asset_updated
      - name: AssetRegistry.MetadataSet
        callback: hydradx.asset.on_metadata_set
      - name: AssetRegistry.LocationSet
        callback: hydradx.asset.on_location_set

      # Stableswap
      - name: Stableswap.PoolCreated
        callback: hydradx.stableswap.on_pool_created
      - name: Stableswap.BuyExecuted
        callback: hydradx.on_swap_executed
      - name: Stableswap.SellExecuted
        callback: hydradx.on_swap_executed
      - name: Stableswap.LiquidityAdded
        callback: hydradx.stableswap.on_liquidity_added
      - name: Stableswap.LiquidityRemoved
        callback: hydradx.stableswap.on_liquidity_removed
