runtimes:
  hydradx:
    kind: substrate
    type_registry: hydration

datasources:
  subsquid:
    kind: substrate.subsquid
    url: https://v2.archive.subsquid.io/network/hydradx
  subscan:
    kind: substrate.subscan
    url: https://hydration.api.subscan.io/api
  node:
    kind: substrate.node
    url: https://rpc.hydradx.cloud
    ws_url: wss://rpc.hydradx.cloud

indexes:
  hydradx_events:
    kind: substrate.events
    runtime: hydradx
    datasources:
      - subsquid
      - subscan
      - node
    handlers:
      - callback: hydradx.on_assetregistry_registered
        name: AssetRegistry.Registered

      # isolated pool example
      - callback: hydradx.on_xyk_buy_executed
        name: XYK.BuyExecuted
      - callback: hydradx.on_xyk_sell_executed
        name: XYK.SellExecuted

      - callback: hydradx.on_omnipool_buy_executed
        name: Omnipool.BuyExecuted
      - callback: hydradx.on_omnipool_sell_executed
        name: Omnipool.SellExecuted

      - callback: hydradx.on_stableswap_buy_executed
        name: Stableswap.BuyExecuted
      - callback: hydradx.on_stableswap_sell_executed
        name: Stableswap.SellExecuted

      - callback: hydradx.on_otc_placed
        name: OTC.Placed
      - callback: hydradx.on_otc_filled
        name: OTC.Filled
      - callback: hydradx.on_otc_partially_filled
        name: OTC.PartiallyFilled
