hasura: null

indexes:
  hydradx_events:
    kind: substrate.events
    runtime: hydradx
    datasources:
      - subsquid
      - subscan
      - node
    handlers:
      # Asset Registry (common)
      - name: AssetRegistry.Registered
        callback: hydradx.asset.on_asset_registered
      - name: AssetRegistry.Updated
        callback: hydradx.asset.on_asset_updated
      - name: AssetRegistry.MetadataSet
        callback: hydradx.asset.on_metadata_set
      - name: AssetRegistry.LocationSet
        callback: hydradx.asset.on_location_set

      # LBP (not in spec)
      - name: LBP.PoolCreated
        callback: hydradx.lbp.on_pool_created
      - name: LBP.PoolUpdated
        callback: hydradx.lbp.on_pool_updated
      - name: LBP.LiquidityAdded
        callback: hydradx.lbp.on_liquidity_added
      - name: LBP.LiquidityRemoved
        callback: hydradx.lbp.on_liquidity_removed
      - name: LBP.BuyExecuted
        callback: hydradx.on_swap_executed
      - name: LBP.SellExecuted
        callback: hydradx.on_swap_executed