# To refresh existing project run `dipdup init --base --force` after modifying this file.
# To generate a new project from this replay run `dipdup new --replay <path_to_file>`.
#
spec_version: 3.0
replay:
  dipdup_version: 8
  template: demo_blank
  package: dex_screener
  version: 0.1.0
  description: DEX Screener indexer
  license: MIT
  name: Baking Bad team
  email: hello@baking-bad.org
  postgres_image: timescale/timescaledb:latest-pg16
  postgres_data_path: /var/lib/postgresql/data
  hasura_image: hasura/graphql-engine:latest
  line_length: 120
  package_manager: uv
