# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V601(TypedDict):
    """
    New metadata has been set for an asset. [asset_id, name, symbol, decimals, is_frozen]
    """

    asset_id: int
    name: list[int]
    symbol: list[int]
    decimals: int
    is_frozen: str
