# generated by DipDup 8.3.2

from __future__ import annotations

from typing import TypedDict

"""
Transfer succeeded. [from, to, value]
"""
V100 = TypedDict(
    'V100',
    {
        'from': str,
        'to': str,
        'value': int,
    },
)
