# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V183(TypedDict):
    """
    New liquidity was provided to the pool.
    """

    who: str
    asset_a: int
    asset_b: int
    amount_a: int
    amount_b: int
