# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V183(TypedDict):
    """
    Asset purchase executed.
    """

    who: str
    asset_out: int
    asset_in: int
    amount: int
    buy_price: int
    fee_asset: int
    fee_amount: int
    pool: str
