# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict

"""
An asset class was destroyed.
"""
V601 = TypedDict(
    'V601',
    {
        'An asset class was destroyed': int,
    },
)
