# generated by DipDup 8.3.3

from __future__ import annotations

from typing import TypedDict


class V100(TypedDict):
    """
    Some amount was withdrawn from the account (e.g. for transaction fees). [who, value]
    """

    who: str
    value: int
