# generated by DipDup 8.4.1

from __future__ import annotations

from typing import TypedDict


class V183(TypedDict):
    """
    A pool was created.
    """

    pool_id: int
    assets: list[int]
    amplification: int
    fee: int
