# generated by DipDup 8.4.2

from __future__ import annotations

from typing import TypedDict


class V176(TypedDict):
    """
    Liquidity was removed from the pool and the pool was destroyed.
    """

    who: str
    asset_a: int
    asset_b: int
    amount_a: int
    amount_b: int
