# generated by DipDup 8.1.3

from __future__ import annotations

from typing import List, TypedDict


class V108(TypedDict):
    """
    Asset was registered. [asset_id, name, type]
    """

    asset_id: int
    name: List[int]
    type: str
