# generated by DipDup 8.1.3

from __future__ import annotations

from typing import List, TypedDict


class V115(TypedDict):
    """
    Asset was registered.
    """

    asset_id: int
    asset_name: List[int]
    asset_type: str
