# generated by DipDup 8.4.1

from __future__ import annotations

from typing import TypedDict


class V115(TypedDict):
    """
    An asset was added to Omnipool
    """

    asset_id: int
    initial_amount: int
    initial_price: int
