# generated by DipDup 8.3.2

from __future__ import annotations

from typing import TypedDict


class V183(TypedDict):
    """
    Buy trade executed. Trade fee paid in asset entering the pool (already included in amount_in).
    """

    who: str
    pool_id: int
    asset_in: int
    asset_out: int
    amount_in: int
    amount_out: int
    fee: int
