# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V183(TypedDict):
    """
    Sell trade executed. Trade fee paid in asset leaving the pool (already subtracted from amount_out).
    """

    who: str
    pool_id: int
    asset_in: int
    asset_out: int
    amount_in: int
    amount_out: int
    fee: int
