# generated by DipDup 8.3.2

from __future__ import annotations

from typing import TypedDict


class V183(TypedDict):
    """
    Asset sale executed.
    """

    who: str
    asset_in: int
    asset_out: int
    amount: int
    sale_price: int
    fee_asset: int
    fee_amount: int
    pool: str
