# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TYPE_CHECKING
from typing import TypedDict

if TYPE_CHECKING:
    from dex_screener.models.dex_fields import Account


class V176(TypedDict):
    """
    Sale executed.
    """

    who: Account
    asset_in: int
    asset_out: int
    amount: int
    sale_price: int
    fee_asset: int
    fee_amount: int
