# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict


class V1002000(TypedDict):
    """
    A successful call of the `AddLiquidity` extrinsic will create this event.
    """

    who: str
    mint_to: str
    pool_id: str
    amount1_provided: int
    amount2_provided: int
    lp_token: int
    lp_token_minted: int
